// <auto-generated />
using System;
using Activate.InterviewProject.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Activate.InterviewProject.Infrastructure.Migrations
{
    [DbContext(typeof(DbContextClass))]
    [Migration("20241210024119_AddingSeededUsers")]
    partial class AddingSeededUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Activate.InterviewProject.Core.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5c3267cd-4935-47da-8279-c37eb3c10e95"),
                            Email = "fry@planetexpress.com",
                            Password = "a37d2472-c93a-4a60-b075-69874c79fb9c",
                            Username = "fry"
                        },
                        new
                        {
                            Id = new Guid("958591fe-68a1-4fea-a5ba-4db02202608d"),
                            Email = "leela@planetexpress.com",
                            Password = "c14e7462-3f8b-4d94-8f1d-1f91ef93eac1",
                            Username = "leela"
                        },
                        new
                        {
                            Id = new Guid("8f06de97-49ec-409c-8e53-e924542c4608"),
                            Email = "bender@planetexpress.com",
                            Password = "63212b3e-d9be-4607-8896-e60fb1b20af8",
                            Username = "bender"
                        },
                        new
                        {
                            Id = new Guid("868b7692-8b2c-457c-8ecc-9f216c364087"),
                            Email = "farnsworth@planetexpress.com",
                            Password = "0803d48a-35b4-476c-994a-558128f11a15",
                            Role = "admin",
                            Username = "professor"
                        },
                        new
                        {
                            Id = new Guid("145aa9ed-7adb-427a-bab2-84e1ff4ece9f"),
                            Email = "amy@planetexpress.com",
                            Password = "c6b53113-56c1-4494-bf99-e0944c825ca2",
                            Username = "amy"
                        },
                        new
                        {
                            Id = new Guid("20bac1cb-deb9-4498-bc2b-8562d6bfc344"),
                            Email = "hermes@planetexpress.com",
                            Password = "5263a605-3c69-4237-b754-27232c5c1978",
                            Username = "hermes"
                        },
                        new
                        {
                            Id = new Guid("addd92a4-8360-4317-bc0e-89bf8c45fada"),
                            Email = "zoidberg@planetexpress.com",
                            Password = "1dd1c2fa-1460-4133-b40b-62e88fdb8ef8",
                            Username = "zoidberg"
                        },
                        new
                        {
                            Id = new Guid("b7887b3d-ef1b-449c-a45e-3cf466ddf9d8"),
                            Email = "zapp@doop.com",
                            Password = "40e8fcbd-fc62-47f4-ae22-7e3bfa4c42c3",
                            Username = "zapp"
                        },
                        new
                        {
                            Id = new Guid("f2cbd456-1161-45c1-831a-28477cd49193"),
                            Email = "kif@doop.com",
                            Password = "4146b3bc-60cc-4212-a15f-27286d306eb0",
                            Username = "kif"
                        },
                        new
                        {
                            Id = new Guid("f7be131a-42b9-4de9-8356-efa7e6fd2fda"),
                            Email = "mom@momcorp.com",
                            Password = "214f2758-a579-436c-88a4-dbf60ddbf1c3",
                            Username = "mom"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
